[[libaec]]
arch = "aarch64"
git-tree-sha1 = "8f43e78c7d5cc53458ca0f5a264607832aefe024"
os = "macos"

    [[libaec.download]]
    sha256 = "d76f1b2d92b5b54d8b0771f8f105f71de50a4b2ae01fe8c46e2d5c4923af1418"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.aarch64-apple-darwin.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "68cbd9a8f6580a9d33c6501949de26aa4f7d62de"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "23c23958b79ee5d411da02fae9e726acf0cf3a8b69fd49e17ace1eca264c397c"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.aarch64-linux-gnu.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "e7d4ccff159c8d7b0c8ba10a02fd4ae0deb51fe8"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "9524cf1a75bc6c28cba74b22bde220deb11a9ca2ad43500ff44f6bd18142f4b9"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.aarch64-linux-musl.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "488c2ea598465bbebf7fe54d40088bf0b6db9d54"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "d1f4b222270e2e8a77a1c148802c59ef3b8f9448d0d866e7619e5b5a8b5dd179"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.armv6l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b4e5d580f76d6e07dff03d37cabaf38a611b5c0"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "130954db81e5d533e067ffab8770c7703016d6ca9fb4fd2b047bdf33ce325e82"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.armv6l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a6c3c32bb9b5c88de3617c22f0db8208ed5a1e6b"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "b9639eaf5579bd959fe6f5c5325eabb272ed0c41149bcb365b89af1a6a49e344"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.armv7l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e46a930e96e3134b96425ca588388d4ec1e4047a"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "0ecb4a9d9ac944464011b750bce804630c6c305d4b6f617b818a61665582145f"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.armv7l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "9e692aeed1f2b8c9c9a82435b7b2ac007ae3aba6"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "afcda91293676492865f0e23a9c70c2a0978a3092c746d6f0645a08aa3ef8b4b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.i686-linux-gnu.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "2c757a51543663591d0e8c73aff7f43491602536"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "a61446fb386e7053e4be095181257c8bcb9eb336f79309f7ec83ff112d740474"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.i686-linux-musl.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "071e3df4147dea87e54605ee4fdcf04381360b1b"
os = "windows"

    [[libaec.download]]
    sha256 = "05c27bcba812abf9e72ae0e833a04165d47fed2c66c0291c16751cd32cc28918"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.i686-w64-mingw32.tar.gz"
[[libaec]]
arch = "powerpc64le"
git-tree-sha1 = "3c13b3007d75ef95c619fec2e269f76630d347a6"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "af58d392b866ca767fbc5d039dc451ce439212863753252e1d441d16c642c69b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.powerpc64le-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "d09fe07c3fc6fa5eb407d4ed108a69939bba73aa"
os = "macos"

    [[libaec.download]]
    sha256 = "5ac2572ae084eee01eb953c70c76592defbb1f8483ec0db65845b385dadb8b77"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.x86_64-apple-darwin.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "47dbf92194a97ba3c70066b4d16e46009d37f34c"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "e54ee3916ab1d807fb1d1f9ff8d769557a1620841ddfcf1c37d00b8325804197"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.x86_64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "ba45ffd931a3ae2673b9ede51cdbeb557f23f298"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "a6d0def7d742bee893b644e458958c566a8123f3ea7f4d96f874edda3df124b5"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.x86_64-linux-musl.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "eac9c69331693c1d50e2dc6c6fd0c7746725e1dc"
os = "freebsd"

    [[libaec.download]]
    sha256 = "9dff8764f160b4ce8fe0806c940718bd7dab3189f34d95faa6b926aafc1c5ba8"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.x86_64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "668337173f9d723787283ee17019c3f502c781ea"
os = "windows"

    [[libaec.download]]
    sha256 = "08d89c4ae8570caa00a884cd3c0a82e67a5baca9f4ab26ed702070a40d0dcd5b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.2+0/libaec.v1.1.2.x86_64-w64-mingw32.tar.gz"
