[[libaec]]
arch = "aarch64"
git-tree-sha1 = "d4f3fcdadb4be9d4872f980facbe5a6623f4f304"
os = "macos"

    [[libaec.download]]
    sha256 = "8ebf76f63c0d6fb87d1f33a8d347fab66ff119f4ab19cac302d892f2bc1b80c6"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.aarch64-apple-darwin.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "e4a8ba52d12b18ef69f8e85dd80ff127eeed9b7b"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "beac3a1dbb9e489ae7ffec7aef27de654bfb78179a9c1dcd74b1ca80d7542579"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.aarch64-linux-gnu.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "5f1a20cd58cbbfdc3c8d80e6f8fd2c4fa0252e8c"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "c5bd349fa9a8b6d3facf3b2167481fef65b21b47e6d13b9a4ade6cefab36c232"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.aarch64-linux-musl.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "36455c06c01a3b16f4d23b40778749e9eeef39ef"
os = "freebsd"

    [[libaec.download]]
    sha256 = "1a3d3fb14b8d311fc8cb9cc229c00aba2cc6d59cf4a40beef7d7ef1025f216f6"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.aarch64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f31a483c01a86c18e90b102585cd487177852407"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "79402d252e5a66df6245d2eb928e98574ff1c49bf095d4f1a710572179cccaf9"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.armv6l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b6869430079cc7a846b6657556b9710cedd980b"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "8a08713b116b8f525d34f6fdbce1bb28d0a8ca8bad1e8afaf3c45e25df4dd117"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.armv6l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1467f392f0a67533c9c3d73f71cfb3508d402d29"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "35193edebf5d370dfff3c56f77ac22934a4ab4171b3b0400697a7ba2ddabf4c0"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.armv7l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "becd3c4bd0d0fb6574ce28478c7f9f0ef0f8ea8e"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "96d7dc027623247bc017d2e212aa34e08d0318a0be31cd156fb48dce7bea90a8"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.armv7l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "1e4cea97397e76e1a70080b09a5b7c769a69add1"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "2d01c788568779f7939130f25289a2000e80436f0e0318b0cefe910f0ed0afac"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.i686-linux-gnu.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "9db478704c04f379ee52c71b177cc7b3cbf26f44"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "31a647639c6682684194e6f960cdc9cc0b3eae4764f95bdc71131ea1532ecd0b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.i686-linux-musl.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "53e99a22957e26511dbc4d20991b2d720ca262a6"
os = "windows"

    [[libaec.download]]
    sha256 = "1dab9d9fbaa8ae26e604edf5db0fa326aa5e63d880311cfb6c79b04eefd00d05"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.i686-w64-mingw32.tar.gz"
[[libaec]]
arch = "powerpc64le"
git-tree-sha1 = "490ef6c0558ca81d3f910f1a4fd04761b5bb3e2e"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "e4bd073cd9033005aa923a01798ca2185a6397ba74cc48722fb00cfdf592829f"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.powerpc64le-linux-gnu.tar.gz"
[[libaec]]
arch = "riscv64"
git-tree-sha1 = "e7f28b571f362c00fcdca6889ec007c545ecf4c5"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "0b55d97f669401629c55e092c4259ce21f3436de6c391389b83bc61627b8bc16"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.riscv64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "4dba62d9bf5aed76505e4815253702105491b001"
os = "macos"

    [[libaec.download]]
    sha256 = "a6264f1e07ea0e42ba1fd7eb4874177c2dc1508f5bf8fdb65ab623e2505b69a8"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.x86_64-apple-darwin.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "72ee04e51b7ed4d8e53a712c7e1d6b236b220092"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "3ebf54c92b1f371d60c685e68e97b3ccea2b4ea6d2c1bbf4403f5eac26d1278a"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.x86_64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "f8e5e625abc518bc5e12cb59f548f8f072d60b20"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "22941eaa9f3787a46062daba7dd3e277506c8394fb38d701abd7eb20669b2ab5"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.x86_64-linux-musl.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "de288a5075fc0732c17203e9e41527f327725659"
os = "freebsd"

    [[libaec.download]]
    sha256 = "cfdec793fdbb13186569e366c382f2ac8ed8d4882f560eb57caff78aa3e0642b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.x86_64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "7b05d9271c60d38d1f9f9605c8b89259077693d8"
os = "windows"

    [[libaec.download]]
    sha256 = "d05a334db2505c56cf2ad75f3e13c4acc93ec7c881e0dfe251f053391332785e"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.3+0/libaec.v1.1.3.x86_64-w64-mingw32.tar.gz"
