[[libaec]]
arch = "aarch64"
git-tree-sha1 = "265d95d398c87b7aeb113ef2dc23b034e0d8addf"
os = "macos"

    [[libaec.download]]
    sha256 = "d6a9b1a13449e52777c818de321b9807fe3fa8ea87e8106997c1d2492f0a80c7"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.aarch64-apple-darwin.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "045eacda87550c9487ba2ffd15e9c7c99a3ced51"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "9b92d93d37302a55e2ec2d435f6b8be0edd0c98fa87757eae65d9e176111260c"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.aarch64-linux-gnu.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "feddf27041c96bca508b00ab6ca74b9ef83724e8"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "4acf462abfceb299547364420332ff93586a0da99364ca656f4b9125e9aaf2a0"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.aarch64-linux-musl.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "cf771106045df466a785b43e3ed84d9701bc7272"
os = "freebsd"

    [[libaec.download]]
    sha256 = "5234c338600539ceee2dee0db6c3972e947a34e121e3e9813ca338d3d9367994"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.aarch64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8fbcdb47b745cc280ce5d193c3bb916c4db0e86"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "d9037cb0923c1877c49f54a99489aca4c975ff96c77da2e96cd4437e88b2e4e7"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.armv6l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c38988e4d3d234ad65270be1a7a340e1727c0e2d"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "8332b31c08811b1916926a5730438dd7b8db7426a88e6a9e0dcf02a4f19942ff"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.armv6l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3897b9e296195a4ca4bc1a920954428992f1a0e0"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "1e0c3e4fdcc8ace50c74c2e62befac2776a0feb1532bbfa4554cd736fc7cda47"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.armv7l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "47893edda5a37258a93faabec1cc5fe457b0f067"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "b619d2a030c2e340703e45a2fc0fa7205bfd6b32bf49559e96ae88045107ade8"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.armv7l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "17b55ef2840b9418b18989ce5a991706acdb7d92"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "ec433ffa89a96dae041fea183088300a2a93ea808ccbbef2121725cae9fa1100"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.i686-linux-gnu.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "42bc3c66f7870e9dfdd24e01d5eaa0c4f01f911d"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "3d9aa900d35a4115e8c73b8011a785bbd150b9e675a89e2c2223315de687c10c"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.i686-linux-musl.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "5c1f4438b09aba0ea6aeb90ec69b970d2c6c04ab"
os = "windows"

    [[libaec.download]]
    sha256 = "a4a8921d337a28c7a1d727ea4a4c97cdf85b5434042c75fea6b1469a82639836"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.i686-w64-mingw32.tar.gz"
[[libaec]]
arch = "powerpc64le"
git-tree-sha1 = "893ea36a2fa69df822b90aaeb1306f982f0cc41c"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "bc59a855ccf798935cf9520e9d272fae59ca9cbb1a3003fd9d52efda0e3af9fc"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.powerpc64le-linux-gnu.tar.gz"
[[libaec]]
arch = "riscv64"
git-tree-sha1 = "c37812a50b05a4a003a855688662b7c125b94e27"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "4b5e59a697f98f2475366d9499e587757b78bbc475a12adad6286d2e6b4570a7"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.riscv64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "7987479c78766c9a721c5e4c53bb112be6695418"
os = "macos"

    [[libaec.download]]
    sha256 = "40f8ca703d62016ea79f23639d385f4211fac9c7b9f067bbb6ab4220cffac1e4"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.x86_64-apple-darwin.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "6d1a77e51584c6ae5747149080022ec2d18a6af1"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "1afe8762138afcd78d71eae6d0482314b42b4b321cead426bb8700fc471adf38"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.x86_64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "786b4df3d2d60286168ca655cdc7943c58f811d5"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "519ae64ee045697b3641bcd2424262c0420a690d25178535fbda63a1f7f1b89d"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.x86_64-linux-musl.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "32f9b4893dec8177cdfb43aa197320c53a11bf01"
os = "freebsd"

    [[libaec.download]]
    sha256 = "661a72a702f0d5449147fdd31cfb8179108e17f6c0a5b5a8a20cf65f2d8597a7"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.x86_64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "72c0d43aa52fd6e2d8794e35fbdf55982b7316a0"
os = "windows"

    [[libaec.download]]
    sha256 = "a4cce4435ccabd18bcf6dc7823a18ef2d3c0c57f8a7cc52956f43ab6a159c991"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.6+0/libaec.v1.1.6.x86_64-w64-mingw32.tar.gz"
