[[libaec]]
arch = "aarch64"
git-tree-sha1 = "1588a056b31dcab981102d5db58aeae781d3d5aa"
os = "macos"

    [[libaec.download]]
    sha256 = "a8001293a5052df34f80543413d59aebd7fec3119dda47b85c38e4f01344c396"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.aarch64-apple-darwin.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "705bf5db103225fcffc14a8ae41c0994a0fe824b"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "42558876b9868f48829a55d698bf6eb8b75ddf13460e795a91bb268a925b39ef"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.aarch64-linux-gnu.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "504836476b968eadcb1c5de6973fffb88aef3124"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "a73cdbbec1954017ab7d16013e787b879001b6855f5aac866a133d4ecde3f316"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.aarch64-linux-musl.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "6e183a136139638a7abce4537eb03fb4bddefdd5"
os = "freebsd"

    [[libaec.download]]
    sha256 = "8f2ad87b837918fc11b1b22aef93e4f18571bacc097009f4e69c5023a88c3174"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.aarch64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a0bc417de4bad8fa12a8975b6fb7dd0c4726499"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "d14523f46013e5e242c29d42af2cb9217ca7333b88948ee15a5b9d114ca7898b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.armv6l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c039f1cbb2b6d9dddf3b2db8da017c7393fd8f73"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "8d7d0729233ccbcf19b37cd3f1821f5d36d47ce7f4c3490133bf6a67eda588fd"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.armv6l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2247daf774536fd979f24bb3a7b5aab25dc60059"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "656131f51f473d8341a80d4cc316f78e2b61ed3c5133021c730aca315ac1c5e1"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.armv7l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "594b2a687f64a7da3bbeb5b8de3a3cc3269fa76c"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "1d16e45e56ccafd8d1e040227aedbe2201bed4c7081983fb1a9ac278f7c8ef38"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.armv7l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "dfb832fd6e2912e2d538c31bc73524a71da0db4b"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "14df8724b1840885c885b8cbe8021e5c0ea4d55ea091a790bcad1a16d5bd3dce"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.i686-linux-gnu.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "6fbd375c5397e12fa37e3ebfaa65ca1402ce9556"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "c44a534510ca151f849827c9e6956796ae0a44a69ee18e63f5319975429a3917"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.i686-linux-musl.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "eebef05c22700c489104d335ff0a9b5307954877"
os = "windows"

    [[libaec.download]]
    sha256 = "7ecd7fc9a4fcd406a7897748855c286ae8ba1bfc67dc57789c9ece67c3b00603"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.i686-w64-mingw32.tar.gz"
[[libaec]]
arch = "powerpc64le"
git-tree-sha1 = "7fe7e4c2a47cdec05234a7519f898c988ce5eca7"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "e8d988d656075760e44babbbe175fdc05d36db7980b8408fe11c0d31f120929e"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.powerpc64le-linux-gnu.tar.gz"
[[libaec]]
arch = "riscv64"
git-tree-sha1 = "91db5112e058d2f64f2717521ff04667868bba31"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "b007bce5098ca3bad8ca76284c47ef85c65e0270ebed7b14756dc88d5aa04b08"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.riscv64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "3b0329b10d044f609e97c4d338cdf435e9ad370d"
os = "macos"

    [[libaec.download]]
    sha256 = "1d5641ed9f515ec15c75441a5918abb8c064bf3f5ce21c7902af9821f4341971"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.x86_64-apple-darwin.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "235aa219585823fcc7f270b3d0efdaec60267f1b"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "f51a62e0ae80a12f60e7549e90db0ed1b463d6084b6061e040f188b3a0aa729f"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.x86_64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "ae98fd22723b6d9eb3fc818e5cb426fa1c75b310"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "6a902457ec95f9d59f0297b7e12f62708c1eb95bdbf81a736be8e332339e5d74"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.x86_64-linux-musl.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "3f5155cdf083336d338c7a87c1157b5c1efaf13f"
os = "freebsd"

    [[libaec.download]]
    sha256 = "8506abd8911d5c492e25fe581a990f618e4e8b9e2a24affc4bdc342836c87d8d"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.x86_64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "34991e28fc12e9d451e2f2b035af296121e67b26"
os = "windows"

    [[libaec.download]]
    sha256 = "fa8743cda094e6ad034dbd09db8bcaaf9c7303c03fe32c9a36353bdb02f38698"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.4+0/libaec.v1.1.4.x86_64-w64-mingw32.tar.gz"
