[[libaec]]
arch = "aarch64"
git-tree-sha1 = "54a671b32d139a5ee9e4f0d1b2941353852b9454"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "1c5f29e1f8142182250e60685ee122cff0a0ac00d165a1a9d0d1ec6e1f844068"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.aarch64-linux-gnu.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "684a5f82fe24f01b5ff711da4d36e41c90b09038"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "13c3e48564fbfac78ec4ce1acf857d5b3bb52de159e1fbf4e02c2b4ac8eb781b"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.aarch64-linux-musl.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "79e75e2d906de2f32dc101b3066ea71bb1ec385d"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "d7da2c1bcd91b0e65c7ee45ea1d8a81ecab6e3e98438d0812798dbf25c9ce2a6"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.armv6l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73c7582386e61677e6c855d75222d54c5139834a"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "0d3fa44209843a657f2cd89555b4f7b8d56658fdd5c2d110ee70f96bd9162d0d"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.armv6l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18a7795b3e4012ee7a7b3d199360cf7f7f5f94e5"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "3c439e350adeb240df7782265793578127dd3bec7e58b5dc12b498d2d79f689f"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.armv7l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50d80848d49ff943d014600de0cf6671f4b2cb3e"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "5175695a1370018c3611c41079321fd02a331388c0a685f8361bf1b3ed6d15d2"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.armv7l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "f221f16331e7568597c3b702c52637f412c254f8"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "536dc116450014131368ccfb28d734658d80f01b88067505aa7373026723f933"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.i686-linux-gnu.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "595ec437fae8717dc8427a0d095dba9fb7f220a6"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "940343dcad9e8af014907545dab7c39749c1f2ca3c12eca710f3642f2f89ce69"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.i686-linux-musl.tar.gz"
[[libaec]]
arch = "powerpc64le"
git-tree-sha1 = "e1990097dc143a8ba2756124da03b5b1501e82c7"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "22b8f1018c38416a86e99af0138e68d19056b3e5086bfeec11dc11f165221a48"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.powerpc64le-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "f5b6e676ae7a0d2740b991083243e0089b81c488"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "03e5d9c43df29bca4f4ba53654b4a369dde8e92f561071825fe79c22b5d0419d"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.x86_64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "223fca5c76559720e6109f24f423be3d31fecc58"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "f4c07170ebcf8a542fa95ca55749ddad64c80a85e185c685d2d4fb8002dfd973"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.0.6+0/libaec.v1.0.6.x86_64-linux-musl.tar.gz"
