[[libaec]]
arch = "aarch64"
git-tree-sha1 = "f7e076ffce5115159c9ea7ef2d257bc5c96d4891"
os = "macos"

    [[libaec.download]]
    sha256 = "8563b62f4fe733530968d14fa89b278102b042bcc1d6d10ec8a53fc157918e89"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.aarch64-apple-darwin.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "3c4f686c92ee2a0289bcacc4efbef7fa47125754"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "a8950d7a29e89921d6e282ce6609834c5f7d6f0f66da6dd5a05a2ce3b358b589"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.aarch64-linux-gnu.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "44e38796e062bf2e31bc16a89ff58006497d49d6"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "e844162d7f3f18b1bedcfc91feefa0ff03709398302743ef012840036c985b02"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.aarch64-linux-musl.tar.gz"
[[libaec]]
arch = "aarch64"
git-tree-sha1 = "c23e154246739e10a1080bb2e3a34c46e493a504"
os = "freebsd"

    [[libaec.download]]
    sha256 = "cbde753226a6779bc5011853bae6679a120f629442342c9d9faa0dbecec0cc10"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.aarch64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e702a5c3bb010d4a7dbed70c3b8b9180be10383d"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "450b937655237052acc554ea7d2c581f55bb93e84c1eb7f3956fb6f68c536fde"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.armv6l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e7915b3b651132edcff289c8b7b53b0f74b67d8"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "eed1aa0fe673fae985aba726e947f51affe72cc623612a8b297500a046a516a8"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.armv6l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87ea273b618c2be3bc2fac956360244d9b5aecd4"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "2565eb51be6c5b8e880d6ec0f5b3b6c23e9b39bebc5565409778748c61ed573e"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.armv7l-linux-gnueabihf.tar.gz"
[[libaec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed4761bd83523a982d8d5193c14f9ffee0c7c45c"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "b2cf23389933683959e7caa15a17c90cceb5d68d1a700e042a1c2cd3ceaa9d33"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.armv7l-linux-musleabihf.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "c79719648065d8ea3de4bb423c2f6c419cffa3e2"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "978976e8785f8624140499f93a26e6141857307aefd0e9269ffd6ff94c42b4a2"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.i686-linux-gnu.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "5253ff325601594b2843a6c92e1598d73d41c782"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "b3bf5e9282a8a7cf02fd51017787c98f889400f518f4831ba624aa8124c2abe8"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.i686-linux-musl.tar.gz"
[[libaec]]
arch = "i686"
git-tree-sha1 = "af0059e0bb20bf96c4d25a1ee35ca669dcdf0a3d"
os = "windows"

    [[libaec.download]]
    sha256 = "10986bc795d13eaec6fb332c1a9a3817b3193cc0b285f25bbc6018b2d952730c"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.i686-w64-mingw32.tar.gz"
[[libaec]]
arch = "powerpc64le"
git-tree-sha1 = "d1dd492a6a92cccf0d55684614ffe586c38eef92"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "66b607871ce720bb9be9c09d2b852c02565e15b9ae38f42d141e18b2aa0ca07c"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.powerpc64le-linux-gnu.tar.gz"
[[libaec]]
arch = "riscv64"
git-tree-sha1 = "736aebe09beed7680b1cfbaf9f3654930f0467d8"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "9eaebdf3134c37b5872363439c9a706b35df12c69ee5967667515bf141c3b53d"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.riscv64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "f8e4f41f399ce0bd750e1f9932122f50c714a58e"
os = "macos"

    [[libaec.download]]
    sha256 = "79c9101d405dfe90271091e829d9dc6605d69a9b6228ddc60f83ab061a83f902"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.x86_64-apple-darwin.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "dc36816ea1be1f788708256dadec7fb61891cc4e"
libc = "glibc"
os = "linux"

    [[libaec.download]]
    sha256 = "04e676783ad3297e6a28f1174104e56be20232a96580b804addd922984821c78"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.x86_64-linux-gnu.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "6e3fc0728f477034fbf92c4e2d38f67adb6ef241"
libc = "musl"
os = "linux"

    [[libaec.download]]
    sha256 = "bcd103c44b295b12c346a38c7d6a2af32d6f3b356e59d15aabad3cde25e9fd9e"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.x86_64-linux-musl.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "0f9004c3f65dbb77160962e13b79ff9a57ed0634"
os = "freebsd"

    [[libaec.download]]
    sha256 = "155509c26ed214bf3048f4355a7587b3d016ae81b4ad0f0f200b184051b38c34"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.x86_64-unknown-freebsd.tar.gz"
[[libaec]]
arch = "x86_64"
git-tree-sha1 = "669ebff27d3142de7b10b2a5647fc433f09078e6"
os = "windows"

    [[libaec.download]]
    sha256 = "f4b5171df59ef4a5e56a7c69764eba60fd9ffde349bbd15eb1487790527a7b73"
    url = "https://github.com/JuliaBinaryWrappers/libaec_jll.jl/releases/download/libaec-v1.1.5+0/libaec.v1.1.5.x86_64-w64-mingw32.tar.gz"
